//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Movilway.API.KinacuLogisticsWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LogisticsInterfaceSoap", Namespace="http://scio-sa.com/webservices/")]
    public partial class LogisticsInterface : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateProductRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateProductDistributionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessProductRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChildRetailersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailableForSaleProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProvidersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetProductStockOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogOffOperationCompleted;
        
        private System.Threading.SendOrPostCallback ChangeUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPrivilegesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LogisticsInterface() {
            this.Url = global::Movilway.API.Properties.Settings.Default.Movilway_API_KinacuLogisticsWebService_LogisticsInterface;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateProductRequestCompletedEventHandler CreateProductRequestCompleted;
        
        /// <remarks/>
        public event CreateProductDistributionCompletedEventHandler CreateProductDistributionCompleted;
        
        /// <remarks/>
        public event GetProductRequestCompletedEventHandler GetProductRequestCompleted;
        
        /// <remarks/>
        public event ProcessProductRequestCompletedEventHandler ProcessProductRequestCompleted;
        
        /// <remarks/>
        public event GetChildRetailersCompletedEventHandler GetChildRetailersCompleted;
        
        /// <remarks/>
        public event GetProductsCompletedEventHandler GetProductsCompleted;
        
        /// <remarks/>
        public event GetAvailableForSaleProductsCompletedEventHandler GetAvailableForSaleProductsCompleted;
        
        /// <remarks/>
        public event GetProvidersCompletedEventHandler GetProvidersCompleted;
        
        /// <remarks/>
        public event GetProductStockCompletedEventHandler GetProductStockCompleted;
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LogOffCompletedEventHandler LogOffCompleted;
        
        /// <remarks/>
        public event ChangeUserPasswordCompletedEventHandler ChangeUserPasswordCompleted;
        
        /// <remarks/>
        public event GetPrivilegesCompletedEventHandler GetPrivilegesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/CreateProductRequest", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateProductRequest(int UserId, int IdProduct, int Amount, out int IdProductRequest, out string Message) {
            object[] results = this.Invoke("CreateProductRequest", new object[] {
                        UserId,
                        IdProduct,
                        Amount});
            IdProductRequest = ((int)(results[1]));
            Message = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateProductRequestAsync(int UserId, int IdProduct, int Amount) {
            this.CreateProductRequestAsync(UserId, IdProduct, Amount, null);
        }
        
        /// <remarks/>
        public void CreateProductRequestAsync(int UserId, int IdProduct, int Amount, object userState) {
            if ((this.CreateProductRequestOperationCompleted == null)) {
                this.CreateProductRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProductRequestOperationCompleted);
            }
            this.InvokeAsync("CreateProductRequest", new object[] {
                        UserId,
                        IdProduct,
                        Amount}, this.CreateProductRequestOperationCompleted, userState);
        }
        
        private void OnCreateProductRequestOperationCompleted(object arg) {
            if ((this.CreateProductRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateProductRequestCompleted(this, new CreateProductRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/CreateProductDistribution", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool CreateProductDistribution(int UserId, decimal RetailerIdTo, int IdProduct, int Amount, out string Message) {
            object[] results = this.Invoke("CreateProductDistribution", new object[] {
                        UserId,
                        RetailerIdTo,
                        IdProduct,
                        Amount});
            Message = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CreateProductDistributionAsync(int UserId, decimal RetailerIdTo, int IdProduct, int Amount) {
            this.CreateProductDistributionAsync(UserId, RetailerIdTo, IdProduct, Amount, null);
        }
        
        /// <remarks/>
        public void CreateProductDistributionAsync(int UserId, decimal RetailerIdTo, int IdProduct, int Amount, object userState) {
            if ((this.CreateProductDistributionOperationCompleted == null)) {
                this.CreateProductDistributionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateProductDistributionOperationCompleted);
            }
            this.InvokeAsync("CreateProductDistribution", new object[] {
                        UserId,
                        RetailerIdTo,
                        IdProduct,
                        Amount}, this.CreateProductDistributionOperationCompleted, userState);
        }
        
        private void OnCreateProductDistributionOperationCompleted(object arg) {
            if ((this.CreateProductDistributionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateProductDistributionCompleted(this, new CreateProductDistributionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/GetProductRequest", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetProductRequest(int UserId, int IdProductRequest, out ProductRequest ProductRequest, out string Message) {
            object[] results = this.Invoke("GetProductRequest", new object[] {
                        UserId,
                        IdProductRequest});
            ProductRequest = ((ProductRequest)(results[1]));
            Message = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductRequestAsync(int UserId, int IdProductRequest) {
            this.GetProductRequestAsync(UserId, IdProductRequest, null);
        }
        
        /// <remarks/>
        public void GetProductRequestAsync(int UserId, int IdProductRequest, object userState) {
            if ((this.GetProductRequestOperationCompleted == null)) {
                this.GetProductRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductRequestOperationCompleted);
            }
            this.InvokeAsync("GetProductRequest", new object[] {
                        UserId,
                        IdProductRequest}, this.GetProductRequestOperationCompleted, userState);
        }
        
        private void OnGetProductRequestOperationCompleted(object arg) {
            if ((this.GetProductRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductRequestCompleted(this, new GetProductRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/ProcessProductRequest", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ProcessProductRequest(int UserId, int IdProductRequest, bool Authorize, out string Message) {
            object[] results = this.Invoke("ProcessProductRequest", new object[] {
                        UserId,
                        IdProductRequest,
                        Authorize});
            Message = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessProductRequestAsync(int UserId, int IdProductRequest, bool Authorize) {
            this.ProcessProductRequestAsync(UserId, IdProductRequest, Authorize, null);
        }
        
        /// <remarks/>
        public void ProcessProductRequestAsync(int UserId, int IdProductRequest, bool Authorize, object userState) {
            if ((this.ProcessProductRequestOperationCompleted == null)) {
                this.ProcessProductRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessProductRequestOperationCompleted);
            }
            this.InvokeAsync("ProcessProductRequest", new object[] {
                        UserId,
                        IdProductRequest,
                        Authorize}, this.ProcessProductRequestOperationCompleted, userState);
        }
        
        private void OnProcessProductRequestOperationCompleted(object arg) {
            if ((this.ProcessProductRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessProductRequestCompleted(this, new ProcessProductRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/GetChildRetailers", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Retailer[] GetChildRetailers(int UserId) {
            object[] results = this.Invoke("GetChildRetailers", new object[] {
                        UserId});
            return ((Retailer[])(results[0]));
        }
        
        /// <remarks/>
        public void GetChildRetailersAsync(int UserId) {
            this.GetChildRetailersAsync(UserId, null);
        }
        
        /// <remarks/>
        public void GetChildRetailersAsync(int UserId, object userState) {
            if ((this.GetChildRetailersOperationCompleted == null)) {
                this.GetChildRetailersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChildRetailersOperationCompleted);
            }
            this.InvokeAsync("GetChildRetailers", new object[] {
                        UserId}, this.GetChildRetailersOperationCompleted, userState);
        }
        
        private void OnGetChildRetailersOperationCompleted(object arg) {
            if ((this.GetChildRetailersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChildRetailersCompleted(this, new GetChildRetailersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/GetProducts", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product[] GetProducts(int UserId) {
            object[] results = this.Invoke("GetProducts", new object[] {
                        UserId});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProductsAsync(int UserId) {
            this.GetProductsAsync(UserId, null);
        }
        
        /// <remarks/>
        public void GetProductsAsync(int UserId, object userState) {
            if ((this.GetProductsOperationCompleted == null)) {
                this.GetProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductsOperationCompleted);
            }
            this.InvokeAsync("GetProducts", new object[] {
                        UserId}, this.GetProductsOperationCompleted, userState);
        }
        
        private void OnGetProductsOperationCompleted(object arg) {
            if ((this.GetProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductsCompleted(this, new GetProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/GetAvailableForSaleProducts", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Product[] GetAvailableForSaleProducts(int UserId) {
            object[] results = this.Invoke("GetAvailableForSaleProducts", new object[] {
                        UserId});
            return ((Product[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailableForSaleProductsAsync(int UserId) {
            this.GetAvailableForSaleProductsAsync(UserId, null);
        }
        
        /// <remarks/>
        public void GetAvailableForSaleProductsAsync(int UserId, object userState) {
            if ((this.GetAvailableForSaleProductsOperationCompleted == null)) {
                this.GetAvailableForSaleProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableForSaleProductsOperationCompleted);
            }
            this.InvokeAsync("GetAvailableForSaleProducts", new object[] {
                        UserId}, this.GetAvailableForSaleProductsOperationCompleted, userState);
        }
        
        private void OnGetAvailableForSaleProductsOperationCompleted(object arg) {
            if ((this.GetAvailableForSaleProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableForSaleProductsCompleted(this, new GetAvailableForSaleProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/GetProviders", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Provider[] GetProviders(int UserId) {
            object[] results = this.Invoke("GetProviders", new object[] {
                        UserId});
            return ((Provider[])(results[0]));
        }
        
        /// <remarks/>
        public void GetProvidersAsync(int UserId) {
            this.GetProvidersAsync(UserId, null);
        }
        
        /// <remarks/>
        public void GetProvidersAsync(int UserId, object userState) {
            if ((this.GetProvidersOperationCompleted == null)) {
                this.GetProvidersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProvidersOperationCompleted);
            }
            this.InvokeAsync("GetProviders", new object[] {
                        UserId}, this.GetProvidersOperationCompleted, userState);
        }
        
        private void OnGetProvidersOperationCompleted(object arg) {
            if ((this.GetProvidersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProvidersCompleted(this, new GetProvidersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/GetProductStock", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetProductStock(int UserId, int IdProduct, out string Message) {
            object[] results = this.Invoke("GetProductStock", new object[] {
                        UserId,
                        IdProduct});
            Message = ((string)(results[1]));
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void GetProductStockAsync(int UserId, int IdProduct) {
            this.GetProductStockAsync(UserId, IdProduct, null);
        }
        
        /// <remarks/>
        public void GetProductStockAsync(int UserId, int IdProduct, object userState) {
            if ((this.GetProductStockOperationCompleted == null)) {
                this.GetProductStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetProductStockOperationCompleted);
            }
            this.InvokeAsync("GetProductStock", new object[] {
                        UserId,
                        IdProduct}, this.GetProductStockOperationCompleted, userState);
        }
        
        private void OnGetProductStockOperationCompleted(object arg) {
            if ((this.GetProductStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetProductStockCompleted(this, new GetProductStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/Login", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Login(string AccessId, string Password, int AccessType, out string Message) {
            object[] results = this.Invoke("Login", new object[] {
                        AccessId,
                        Password,
                        AccessType});
            Message = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string AccessId, string Password, int AccessType) {
            this.LoginAsync(AccessId, Password, AccessType, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string AccessId, string Password, int AccessType, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        AccessId,
                        Password,
                        AccessType}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/LogOff", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LogOff(int UserId) {
            this.Invoke("LogOff", new object[] {
                        UserId});
        }
        
        /// <remarks/>
        public void LogOffAsync(int UserId) {
            this.LogOffAsync(UserId, null);
        }
        
        /// <remarks/>
        public void LogOffAsync(int UserId, object userState) {
            if ((this.LogOffOperationCompleted == null)) {
                this.LogOffOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogOffOperationCompleted);
            }
            this.InvokeAsync("LogOff", new object[] {
                        UserId}, this.LogOffOperationCompleted, userState);
        }
        
        private void OnLogOffOperationCompleted(object arg) {
            if ((this.LogOffCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogOffCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/ChangeUserPassword", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ChangeUserPassword(int UserId, string OldPassword, string NewPassword, out string Message) {
            object[] results = this.Invoke("ChangeUserPassword", new object[] {
                        UserId,
                        OldPassword,
                        NewPassword});
            Message = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ChangeUserPasswordAsync(int UserId, string OldPassword, string NewPassword) {
            this.ChangeUserPasswordAsync(UserId, OldPassword, NewPassword, null);
        }
        
        /// <remarks/>
        public void ChangeUserPasswordAsync(int UserId, string OldPassword, string NewPassword, object userState) {
            if ((this.ChangeUserPasswordOperationCompleted == null)) {
                this.ChangeUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeUserPasswordOperationCompleted);
            }
            this.InvokeAsync("ChangeUserPassword", new object[] {
                        UserId,
                        OldPassword,
                        NewPassword}, this.ChangeUserPasswordOperationCompleted, userState);
        }
        
        private void OnChangeUserPasswordOperationCompleted(object arg) {
            if ((this.ChangeUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeUserPasswordCompleted(this, new ChangeUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://scio-sa.com/webservices/GetPrivileges", RequestNamespace="http://scio-sa.com/webservices/", ResponseNamespace="http://scio-sa.com/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetPrivileges(int UserId, string Type, out PrivilegeInfo[] Privileges, out string Message) {
            object[] results = this.Invoke("GetPrivileges", new object[] {
                        UserId,
                        Type});
            Privileges = ((PrivilegeInfo[])(results[1]));
            Message = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetPrivilegesAsync(int UserId, string Type) {
            this.GetPrivilegesAsync(UserId, Type, null);
        }
        
        /// <remarks/>
        public void GetPrivilegesAsync(int UserId, string Type, object userState) {
            if ((this.GetPrivilegesOperationCompleted == null)) {
                this.GetPrivilegesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPrivilegesOperationCompleted);
            }
            this.InvokeAsync("GetPrivileges", new object[] {
                        UserId,
                        Type}, this.GetPrivilegesOperationCompleted, userState);
        }
        
        private void OnGetPrivilegesOperationCompleted(object arg) {
            if ((this.GetPrivilegesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPrivilegesCompleted(this, new GetPrivilegesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scio-sa.com/webservices/")]
    public partial class ProductRequest {
        
        private int productRequestIdField;
        
        private string retailerNameSourceField;
        
        private int retailerIdSourceField;
        
        private System.DateTime dateField;
        
        private string stateField;
        
        private long amountField;
        
        /// <remarks/>
        public int ProductRequestId {
            get {
                return this.productRequestIdField;
            }
            set {
                this.productRequestIdField = value;
            }
        }
        
        /// <remarks/>
        public string RetailerNameSource {
            get {
                return this.retailerNameSourceField;
            }
            set {
                this.retailerNameSourceField = value;
            }
        }
        
        /// <remarks/>
        public int RetailerIdSource {
            get {
                return this.retailerIdSourceField;
            }
            set {
                this.retailerIdSourceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public long Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scio-sa.com/webservices/")]
    public partial class PrivilegeInfo {
        
        private decimal idField;
        
        private string nameField;
        
        private string valueField;
        
        private string typeField;
        
        private decimal parentIdField;
        
        /// <remarks/>
        public decimal Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public decimal ParentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scio-sa.com/webservices/")]
    public partial class Provider {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scio-sa.com/webservices/")]
    public partial class Product {
        
        private int idField;
        
        private string nameField;
        
        private int[] providerIdField;
        
        private int moduleIdField;
        
        private bool availableForPurchaseField;
        
        private bool availableForSaleField;
        
        private string currencySymbolField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public int[] ProviderId {
            get {
                return this.providerIdField;
            }
            set {
                this.providerIdField = value;
            }
        }
        
        /// <remarks/>
        public int ModuleId {
            get {
                return this.moduleIdField;
            }
            set {
                this.moduleIdField = value;
            }
        }
        
        /// <remarks/>
        public bool AvailableForPurchase {
            get {
                return this.availableForPurchaseField;
            }
            set {
                this.availableForPurchaseField = value;
            }
        }
        
        /// <remarks/>
        public bool AvailableForSale {
            get {
                return this.availableForSaleField;
            }
            set {
                this.availableForSaleField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencySymbol {
            get {
                return this.currencySymbolField;
            }
            set {
                this.currencySymbolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://scio-sa.com/webservices/")]
    public partial class Retailer {
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateProductRequestCompletedEventHandler(object sender, CreateProductRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateProductRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateProductRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int IdProductRequest {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateProductDistributionCompletedEventHandler(object sender, CreateProductDistributionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateProductDistributionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateProductDistributionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductRequestCompletedEventHandler(object sender, GetProductRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ProductRequest ProductRequest {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductRequest)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ProcessProductRequestCompletedEventHandler(object sender, ProcessProductRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessProductRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessProductRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetChildRetailersCompletedEventHandler(object sender, GetChildRetailersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChildRetailersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChildRetailersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retailer[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retailer[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductsCompletedEventHandler(object sender, GetProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAvailableForSaleProductsCompletedEventHandler(object sender, GetAvailableForSaleProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailableForSaleProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableForSaleProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Product[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Product[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProvidersCompletedEventHandler(object sender, GetProvidersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProvidersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProvidersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Provider[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Provider[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetProductStockCompletedEventHandler(object sender, GetProductStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetProductStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetProductStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void LogOffCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ChangeUserPasswordCompletedEventHandler(object sender, ChangeUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ChangeUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetPrivilegesCompletedEventHandler(object sender, GetPrivilegesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPrivilegesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPrivilegesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public PrivilegeInfo[] Privileges {
            get {
                this.RaiseExceptionIfNecessary();
                return ((PrivilegeInfo[])(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591