//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.IBank {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBalanceRequest", Namespace="http://movilway.net/schema/ibank")]
    [System.SerializableAttribute()]
    public partial class GetBalanceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNationalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Agent {
            get {
                return this.AgentField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentField, value) != true)) {
                    this.AgentField = value;
                    this.RaisePropertyChanged("Agent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AgentNationalID {
            get {
                return this.AgentNationalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNationalIDField, value) != true)) {
                    this.AgentNationalIDField = value;
                    this.RaisePropertyChanged("AgentNationalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBalanceResponse", Namespace="http://movilway.net/schema/ibank")]
    [System.SerializableAttribute()]
    public partial class GetBalanceResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalTransactionReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movilway.API.IBank.Balances BalancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ApprovedAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal ConsumedAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AvailableAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal NextPaymentAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NextPaymentDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ExternalTransactionReference {
            get {
                return this.ExternalTransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalTransactionReferenceField, value) != true)) {
                    this.ExternalTransactionReferenceField = value;
                    this.RaisePropertyChanged("ExternalTransactionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Movilway.API.IBank.Balances Balances {
            get {
                return this.BalancesField;
            }
            set {
                if ((object.ReferenceEquals(this.BalancesField, value) != true)) {
                    this.BalancesField = value;
                    this.RaisePropertyChanged("Balances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal ApprovedAmount {
            get {
                return this.ApprovedAmountField;
            }
            set {
                if ((this.ApprovedAmountField.Equals(value) != true)) {
                    this.ApprovedAmountField = value;
                    this.RaisePropertyChanged("ApprovedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal ConsumedAmount {
            get {
                return this.ConsumedAmountField;
            }
            set {
                if ((this.ConsumedAmountField.Equals(value) != true)) {
                    this.ConsumedAmountField = value;
                    this.RaisePropertyChanged("ConsumedAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal AvailableAmount {
            get {
                return this.AvailableAmountField;
            }
            set {
                if ((this.AvailableAmountField.Equals(value) != true)) {
                    this.AvailableAmountField = value;
                    this.RaisePropertyChanged("AvailableAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal NextPaymentAmount {
            get {
                return this.NextPaymentAmountField;
            }
            set {
                if ((this.NextPaymentAmountField.Equals(value) != true)) {
                    this.NextPaymentAmountField = value;
                    this.RaisePropertyChanged("NextPaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string NextPaymentDate {
            get {
                return this.NextPaymentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.NextPaymentDateField, value) != true)) {
                    this.NextPaymentDateField = value;
                    this.RaisePropertyChanged("NextPaymentDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Balances", Namespace="http://movilway.net/schema/ibank", ItemName="Balance")]
    [System.SerializableAttribute()]
    public class Balances : System.Collections.Generic.List<Movilway.API.IBank.Balance> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Balance", Namespace="http://movilway.net/schema/ibank")]
    [System.SerializableAttribute()]
    public partial class Balance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TypeField;
        
        private decimal AmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTransactionRequest", Namespace="http://movilway.net/schema/ibank")]
    [System.SerializableAttribute()]
    public partial class ProcessTransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TransactionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionReferenceField;
        
        private string AgentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentNationalIDField;
        
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movilway.API.IBank.AdditionalData AdditionalDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string TransactionType {
            get {
                return this.TransactionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionTypeField, value) != true)) {
                    this.TransactionTypeField = value;
                    this.RaisePropertyChanged("TransactionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TransactionReference {
            get {
                return this.TransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionReferenceField, value) != true)) {
                    this.TransactionReferenceField = value;
                    this.RaisePropertyChanged("TransactionReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string Agent {
            get {
                return this.AgentField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentField, value) != true)) {
                    this.AgentField = value;
                    this.RaisePropertyChanged("Agent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string AgentNationalID {
            get {
                return this.AgentNationalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentNationalIDField, value) != true)) {
                    this.AgentNationalIDField = value;
                    this.RaisePropertyChanged("AgentNationalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Movilway.API.IBank.AdditionalData AdditionalData {
            get {
                return this.AdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalDataField, value) != true)) {
                    this.AdditionalDataField = value;
                    this.RaisePropertyChanged("AdditionalData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="AdditionalData", Namespace="http://movilway.net/schema/ibank", ItemName="AdditionalData", KeyName="Key", ValueName="Value")]
    [System.SerializableAttribute()]
    public class AdditionalData : System.Collections.Generic.Dictionary<string, string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessTransactionResponse", Namespace="http://movilway.net/schema/ibank")]
    [System.SerializableAttribute()]
    public partial class ProcessTransactionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        private string ResponseMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExternalTransactionReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ResponseMessage {
            get {
                return this.ResponseMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseMessageField, value) != true)) {
                    this.ResponseMessageField = value;
                    this.RaisePropertyChanged("ResponseMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExternalTransactionReference {
            get {
                return this.ExternalTransactionReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExternalTransactionReferenceField, value) != true)) {
                    this.ExternalTransactionReferenceField = value;
                    this.RaisePropertyChanged("ExternalTransactionReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://movilway.net/schema/ibank/services", ConfigurationName="IBank.IIBankService")]
    public interface IIBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://movilway.net/schema/ibank/services/IIBankService/GetBalance", ReplyAction="http://movilway.net/schema/ibank/services/IIBankService/GetBalanceResponse")]
        Movilway.API.IBank.GetBalanceResponse GetBalance(Movilway.API.IBank.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://movilway.net/schema/ibank/services/IIBankService/GetBalance", ReplyAction="http://movilway.net/schema/ibank/services/IIBankService/GetBalanceResponse")]
        System.Threading.Tasks.Task<Movilway.API.IBank.GetBalanceResponse> GetBalanceAsync(Movilway.API.IBank.GetBalanceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://movilway.net/schema/ibank/services/IIBankService/ProcessTransaction", ReplyAction="http://movilway.net/schema/ibank/services/IIBankService/ProcessTransactionRespons" +
            "e")]
        Movilway.API.IBank.ProcessTransactionResponse ProcessTransaction(Movilway.API.IBank.ProcessTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://movilway.net/schema/ibank/services/IIBankService/ProcessTransaction", ReplyAction="http://movilway.net/schema/ibank/services/IIBankService/ProcessTransactionRespons" +
            "e")]
        System.Threading.Tasks.Task<Movilway.API.IBank.ProcessTransactionResponse> ProcessTransactionAsync(Movilway.API.IBank.ProcessTransactionRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIBankServiceChannel : Movilway.API.IBank.IIBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IBankServiceClient : System.ServiceModel.ClientBase<Movilway.API.IBank.IIBankService>, Movilway.API.IBank.IIBankService {
        
        public IBankServiceClient() {
        }
        
        public IBankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IBankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IBankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IBankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Movilway.API.IBank.GetBalanceResponse GetBalance(Movilway.API.IBank.GetBalanceRequest request) {
            return base.Channel.GetBalance(request);
        }
        
        public System.Threading.Tasks.Task<Movilway.API.IBank.GetBalanceResponse> GetBalanceAsync(Movilway.API.IBank.GetBalanceRequest request) {
            return base.Channel.GetBalanceAsync(request);
        }
        
        public Movilway.API.IBank.ProcessTransactionResponse ProcessTransaction(Movilway.API.IBank.ProcessTransactionRequest request) {
            return base.Channel.ProcessTransaction(request);
        }
        
        public System.Threading.Tasks.Task<Movilway.API.IBank.ProcessTransactionResponse> ProcessTransactionAsync(Movilway.API.IBank.ProcessTransactionRequest request) {
            return base.Channel.ProcessTransactionAsync(request);
        }
    }
}
