//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Access
    {
        public int AccessTypeId { get; set; }
        public int PlatformId { get; set; }
        public int CountryId { get; set; }
        public int UserId { get; set; }
        public string StatusId { get; set; }
        public Nullable<System.DateTime> DateLastLogin { get; set; }
        public string Login { get; set; }
    
        public virtual AccessType AccessType { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
    }
}
