//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditMessage
    {
        public int MessageId { get; set; }
        public int ScheduleId { get; set; }
        public int CountryId { get; set; }
        public int PlatformId { get; set; }
        public int BranchId { get; set; }
        public Nullable<int> ParentBranchId { get; set; }
        public int UserId { get; set; }
        public int DeliveryCounter { get; set; }
        public System.DateTimeOffset FirstDeliveryDateTime { get; set; }
        public System.DateTimeOffset LastDeliveryDateTime { get; set; }
        public int ReadCounter { get; set; }
        public Nullable<System.DateTimeOffset> FirstReadDateTime { get; set; }
        public Nullable<System.DateTimeOffset> LastReadDateTime { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Country Country { get; set; }
        public virtual Message Message { get; set; }
        public virtual Branch Branch1 { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual User User { get; set; }
    }
}
