//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditMessageScheduleEntry
    {
        public int MessageScheduleId { get; set; }
        public int MessageId { get; set; }
        public string Frecuency { get; set; }
        public string Days { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
        public System.DateTimeOffset DateTime { get; set; }
        public int ACLUserId { get; set; }
        public string ACLUserLogin { get; set; }
        public string HostAddress { get; set; }
        public string HostName { get; set; }
        public string StatusId { get; set; }
    
        public virtual MessageSchedule MessageSchedule { get; set; }
    }
}
