//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditMessageTicketEntry
    {
        public int MessageId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IncludeSubBranches { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public string MessageDestination { get; set; }
        public int MessageTypeId { get; set; }
        public string StatusId { get; set; }
        public int PrintingMaximumCounter { get; set; }
        public string ProviderIdList { get; set; }
        public string ProductIdList { get; set; }
        public string AccessTypeIdList { get; set; }
        public System.DateTimeOffset DateTime { get; set; }
        public int ACLUserId { get; set; }
        public string ACLUserLogin { get; set; }
        public string HostAddress { get; set; }
        public string HostName { get; set; }
    
        public virtual MessageTicket MessageTicket { get; set; }
    }
}
