//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Messages = new HashSet<Message>();
            this.MessageTickets = new HashSet<MessageTicket>();
            this.Products = new HashSet<Product>();
            this.Provinces = new HashSet<Province>();
            this.AuditMessages = new HashSet<AuditMessage>();
            this.AuditMessageTickets = new HashSet<AuditMessageTicket>();
        }
    
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public double TimeZone { get; set; }
        public string Acronym { get; set; }
        public string Acronym3 { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageTicket> MessageTickets { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Province> Provinces { get; set; }
        public virtual ICollection<AuditMessage> AuditMessages { get; set; }
        public virtual ICollection<AuditMessageTicket> AuditMessageTickets { get; set; }
    }
}
