//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public Message()
        {
            this.AuditMessageEntries = new HashSet<AuditMessageEntry>();
            this.MessageSchedules = new HashSet<MessageSchedule>();
            this.AccessTypes = new HashSet<AccessType>();
            this.Products = new HashSet<Product>();
            this.Providers = new HashSet<Provider>();
            this.AuditMessages = new HashSet<AuditMessage>();
        }
    
        public int MessageId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public Nullable<int> ProvinceId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public bool IncludeSubBranches { get; set; }
        public string Title { get; set; }
        public string Abstract { get; set; }
        public string Detail { get; set; }
        public string ImageURL { get; set; }
        public string MessageDestination { get; set; }
        public int MessageTypeId { get; set; }
        public string StatusId { get; set; }
        public int DeliveryMaximumCounter { get; set; }
        public System.DateTimeOffset CreationDateTime { get; set; }
        public int CreationACLUserId { get; set; }
        public string CreationACLUserLogin { get; set; }
        public string CreationHostAddress { get; set; }
        public string CreationHostName { get; set; }
    
        public virtual ICollection<AuditMessageEntry> AuditMessageEntries { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual MessageType MessageType { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Province Province { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<MessageSchedule> MessageSchedules { get; set; }
        public virtual ICollection<AccessType> AccessTypes { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<Provider> Providers { get; set; }
        public virtual ICollection<AuditMessage> AuditMessages { get; set; }
    }
}
