//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotiwayEntities : DbContext
    {
        public NotiwayEntities()
            : base("name=NotiwayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AccessType> AccessTypes { get; set; }
        public DbSet<AuditMessageEntry> AuditMessageEntries { get; set; }
        public DbSet<AuditMessageScheduleEntry> AuditMessageScheduleEntries { get; set; }
        public DbSet<AuditMessageTicketEntry> AuditMessageTicketEntries { get; set; }
        public DbSet<AuditMessageTicketScheduleEntry> AuditMessageTicketScheduleEntries { get; set; }
        public DbSet<Branch> Branches { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<Country> Countries { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<MessageSchedule> MessageSchedules { get; set; }
        public DbSet<MessageTicket> MessageTickets { get; set; }
        public DbSet<MessageTicketSchedule> MessageTicketSchedules { get; set; }
        public DbSet<MessageType> MessageTypes { get; set; }
        public DbSet<Platform> Platforms { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Provider> Providers { get; set; }
        public DbSet<Province> Provinces { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Access> Accesses { get; set; }
        public DbSet<BranchProduct> BranchProducts { get; set; }
        public DbSet<AuditMessage> AuditMessages { get; set; }
        public DbSet<AuditMessageTicket> AuditMessageTickets { get; set; }
    }
}
