//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Messages = new HashSet<Message>();
            this.MessageTickets = new HashSet<MessageTicket>();
        }
    
        public int ProductId { get; set; }
        public int PlatformId { get; set; }
        public int CountryId { get; set; }
        public int ProviderId { get; set; }
        public string ProductName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public decimal Stock { get; set; }
        public Nullable<System.DateTime> DateLastPurchase { get; set; }
        public string StatusId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Status Status { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageTicket> MessageTickets { get; set; }
    }
}
