//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.Branches = new HashSet<Branch>();
            this.Messages = new HashSet<Message>();
            this.MessageTickets = new HashSet<MessageTicket>();
            this.Products = new HashSet<Product>();
            this.Users = new HashSet<User>();
            this.MessageSchedules = new HashSet<MessageSchedule>();
            this.MessageTicketSchedules = new HashSet<MessageTicketSchedule>();
            this.Accesses = new HashSet<Access>();
        }
    
        public string StatusId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Branch> Branches { get; set; }
        public virtual ICollection<Message> Messages { get; set; }
        public virtual ICollection<MessageTicket> MessageTickets { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual ICollection<MessageSchedule> MessageSchedules { get; set; }
        public virtual ICollection<MessageTicketSchedule> MessageTicketSchedules { get; set; }
        public virtual ICollection<Access> Accesses { get; set; }
    }
}
