//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.Notiway
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accesses = new HashSet<Access>();
            this.AuditMessages = new HashSet<AuditMessage>();
            this.AuditMessageTickets = new HashSet<AuditMessageTicket>();
        }
    
        public int UserId { get; set; }
        public int PlatformId { get; set; }
        public int CountryId { get; set; }
        public int ProvinceId { get; set; }
        public int CityId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int BranchId { get; set; }
        public string StatusId { get; set; }
        public string UserReference { get; set; }
        public string UserName { get; set; }
        public string Surname { get; set; }
        public string DocumentType { get; set; }
        public string DocumentNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string CellPhone { get; set; }
        public string Neighborhood { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> DateSignOn { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual City City { get; set; }
        public virtual Platform Platform { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual ICollection<Access> Accesses { get; set; }
        public virtual ICollection<AuditMessage> AuditMessages { get; set; }
        public virtual ICollection<AuditMessageTicket> AuditMessageTickets { get; set; }
    }
}
