//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.PSE_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.enlineapagos.com/secure/webservices", ConfigurationName="PSE_WS.PSEPortType")]
    public interface PSEPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.enlineapagos.com/secure/webservices/WS_PSE.do/Listar_Bancos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.PSE_WS.Listar_BancosResponse Listar_Bancos(Movilway.API.PSE_WS.Listar_BancosRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.enlineapagos.com/secure/webservices/WS_PSE.do/Listar_Bancos", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.PSE_WS.Listar_BancosResponse> Listar_BancosAsync(Movilway.API.PSE_WS.Listar_BancosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.enlineapagos.com/secure/webservices/WS_PSE.do/Iniciar_Pago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.PSE_WS.Iniciar_PagoResponse Iniciar_Pago(Movilway.API.PSE_WS.Iniciar_PagoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.enlineapagos.com/secure/webservices/WS_PSE.do/Iniciar_Pago", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.PSE_WS.Iniciar_PagoResponse> Iniciar_PagoAsync(Movilway.API.PSE_WS.Iniciar_PagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.enlineapagos.com/secure/webservices/WS_PSE.do/Confirma_Respuesta_Pago" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.PSE_WS.Confirma_Respuesta_PagoResponse Confirma_Respuesta_Pago(Movilway.API.PSE_WS.Confirma_Respuesta_PagoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://www.enlineapagos.com/secure/webservices/WS_PSE.do/Confirma_Respuesta_Pago" +
            "", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.PSE_WS.Confirma_Respuesta_PagoResponse> Confirma_Respuesta_PagoAsync(Movilway.API.PSE_WS.Confirma_Respuesta_PagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar_Bancos", WrapperNamespace="https://www.enlineapagos.com/secure/webservices", IsWrapped=true)]
    public partial class Listar_BancosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        public Listar_BancosRequest() {
        }
        
        public Listar_BancosRequest(string usuario, string clave, string llavemd5) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Listar_BancosResponse", WrapperNamespace="https://www.enlineapagos.com/secure/webservices", IsWrapped=true)]
    public partial class Listar_BancosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string errorsms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string listabancos;
        
        public Listar_BancosResponse() {
        }
        
        public Listar_BancosResponse(string respuesta, string errorsms, string listabancos) {
            this.respuesta = respuesta;
            this.errorsms = errorsms;
            this.listabancos = listabancos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Iniciar_Pago", WrapperNamespace="https://www.enlineapagos.com/secure/webservices", IsWrapped=true)]
    public partial class Iniciar_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string total_con_iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string valor_iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string descripcion_pago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string Id_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string nombre_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string apellido_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string telefono_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string pais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string ciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string ip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public string firma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string info_opcional1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string info_opcional2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string info_opcional3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public string lista_codigos_servicio_multicredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string lista_nit_codigos_servicio_multicredito;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string lista_valores_con_iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=23)]
        public string lista_valores_iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=24)]
        public string total_codigos_servicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=25)]
        public string fotografiaurl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=26)]
        public string grabacionurl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=27)]
        public string llamadaconfirmacionnumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=28)]
        public string facebook;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=29)]
        public string urlretorno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=30)]
        public string CodigoDelBanco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=31)]
        public string TipoDeUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=32)]
        public string latitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=33)]
        public string longitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=34)]
        public string exactitud;
        
        public Iniciar_PagoRequest() {
        }
        
        public Iniciar_PagoRequest(
                    string usuario, 
                    string clave, 
                    string llavemd5, 
                    string referencia, 
                    string total_con_iva, 
                    string valor_iva, 
                    string descripcion_pago, 
                    string email, 
                    string Id_cliente, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string direccion, 
                    string pais, 
                    string ciudad, 
                    string ip, 
                    string firma, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string lista_codigos_servicio_multicredito, 
                    string lista_nit_codigos_servicio_multicredito, 
                    string lista_valores_con_iva, 
                    string lista_valores_iva, 
                    string total_codigos_servicio, 
                    string fotografiaurl, 
                    string grabacionurl, 
                    string llamadaconfirmacionnumero, 
                    string facebook, 
                    string urlretorno, 
                    string CodigoDelBanco, 
                    string TipoDeUsuario, 
                    string latitud, 
                    string longitud, 
                    string exactitud) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.referencia = referencia;
            this.total_con_iva = total_con_iva;
            this.valor_iva = valor_iva;
            this.descripcion_pago = descripcion_pago;
            this.email = email;
            this.Id_cliente = Id_cliente;
            this.nombre_cliente = nombre_cliente;
            this.apellido_cliente = apellido_cliente;
            this.telefono_cliente = telefono_cliente;
            this.direccion = direccion;
            this.pais = pais;
            this.ciudad = ciudad;
            this.ip = ip;
            this.firma = firma;
            this.info_opcional1 = info_opcional1;
            this.info_opcional2 = info_opcional2;
            this.info_opcional3 = info_opcional3;
            this.lista_codigos_servicio_multicredito = lista_codigos_servicio_multicredito;
            this.lista_nit_codigos_servicio_multicredito = lista_nit_codigos_servicio_multicredito;
            this.lista_valores_con_iva = lista_valores_con_iva;
            this.lista_valores_iva = lista_valores_iva;
            this.total_codigos_servicio = total_codigos_servicio;
            this.fotografiaurl = fotografiaurl;
            this.grabacionurl = grabacionurl;
            this.llamadaconfirmacionnumero = llamadaconfirmacionnumero;
            this.facebook = facebook;
            this.urlretorno = urlretorno;
            this.CodigoDelBanco = CodigoDelBanco;
            this.TipoDeUsuario = TipoDeUsuario;
            this.latitud = latitud;
            this.longitud = longitud;
            this.exactitud = exactitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Iniciar_PagoResponse", WrapperNamespace="https://www.enlineapagos.com/secure/webservices", IsWrapped=true)]
    public partial class Iniciar_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string errorsms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string numerotransaccion;
        
        public Iniciar_PagoResponse() {
        }
        
        public Iniciar_PagoResponse(string respuesta, string errorsms, string url, string numerotransaccion) {
            this.respuesta = respuesta;
            this.errorsms = errorsms;
            this.url = url;
            this.numerotransaccion = numerotransaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Confirma_Respuesta_Pago", WrapperNamespace="https://www.enlineapagos.com/secure/webservices", IsWrapped=true)]
    public partial class Confirma_Respuesta_PagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string numerotransaccion;
        
        public Confirma_Respuesta_PagoRequest() {
        }
        
        public Confirma_Respuesta_PagoRequest(string usuario, string clave, string llavemd5, string numerotransaccion) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.numerotransaccion = numerotransaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Confirma_Respuesta_PagoResponse", WrapperNamespace="https://www.enlineapagos.com/secure/webservices", IsWrapped=true)]
    public partial class Confirma_Respuesta_PagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string errorsms;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string int_estado_pago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string str_nombre_banco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string str_codigo_transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string int_ciclo_transaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string dat_fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string fechatransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string horatransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string descripcion_pago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string nombre_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string apellido_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string telefono_cliente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string pais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public string ciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string info_opcional1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string info_opcional2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string info_opcional3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public string firma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string ip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string total_con_iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=23)]
        public string valor_iva;
        
        public Confirma_Respuesta_PagoResponse() {
        }
        
        public Confirma_Respuesta_PagoResponse(
                    string respuesta, 
                    string errorsms, 
                    string int_estado_pago, 
                    string str_nombre_banco, 
                    string str_codigo_transaccion, 
                    string int_ciclo_transaccion, 
                    string dat_fecha, 
                    string fechatransaccion, 
                    string horatransaccion, 
                    string descripcion_pago, 
                    string email, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string direccion, 
                    string pais, 
                    string ciudad, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string firma, 
                    string ip, 
                    string total_con_iva, 
                    string valor_iva) {
            this.respuesta = respuesta;
            this.errorsms = errorsms;
            this.int_estado_pago = int_estado_pago;
            this.str_nombre_banco = str_nombre_banco;
            this.str_codigo_transaccion = str_codigo_transaccion;
            this.int_ciclo_transaccion = int_ciclo_transaccion;
            this.dat_fecha = dat_fecha;
            this.fechatransaccion = fechatransaccion;
            this.horatransaccion = horatransaccion;
            this.descripcion_pago = descripcion_pago;
            this.email = email;
            this.nombre_cliente = nombre_cliente;
            this.apellido_cliente = apellido_cliente;
            this.telefono_cliente = telefono_cliente;
            this.direccion = direccion;
            this.pais = pais;
            this.ciudad = ciudad;
            this.info_opcional1 = info_opcional1;
            this.info_opcional2 = info_opcional2;
            this.info_opcional3 = info_opcional3;
            this.firma = firma;
            this.ip = ip;
            this.total_con_iva = total_con_iva;
            this.valor_iva = valor_iva;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PSEPortTypeChannel : Movilway.API.PSE_WS.PSEPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PSEPortTypeClient : System.ServiceModel.ClientBase<Movilway.API.PSE_WS.PSEPortType>, Movilway.API.PSE_WS.PSEPortType {
        
        public PSEPortTypeClient() {
        }
        
        public PSEPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PSEPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSEPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PSEPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.PSE_WS.Listar_BancosResponse Movilway.API.PSE_WS.PSEPortType.Listar_Bancos(Movilway.API.PSE_WS.Listar_BancosRequest request) {
            return base.Channel.Listar_Bancos(request);
        }
        
        public string Listar_Bancos(string usuario, string clave, string llavemd5, out string errorsms, out string listabancos) {
            Movilway.API.PSE_WS.Listar_BancosRequest inValue = new Movilway.API.PSE_WS.Listar_BancosRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            Movilway.API.PSE_WS.Listar_BancosResponse retVal = ((Movilway.API.PSE_WS.PSEPortType)(this)).Listar_Bancos(inValue);
            errorsms = retVal.errorsms;
            listabancos = retVal.listabancos;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.PSE_WS.Listar_BancosResponse> Listar_BancosAsync(Movilway.API.PSE_WS.Listar_BancosRequest request) {
            return base.Channel.Listar_BancosAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.PSE_WS.Iniciar_PagoResponse Movilway.API.PSE_WS.PSEPortType.Iniciar_Pago(Movilway.API.PSE_WS.Iniciar_PagoRequest request) {
            return base.Channel.Iniciar_Pago(request);
        }
        
        public string Iniciar_Pago(
                    string usuario, 
                    string clave, 
                    string llavemd5, 
                    string referencia, 
                    string total_con_iva, 
                    string valor_iva, 
                    string descripcion_pago, 
                    string email, 
                    string Id_cliente, 
                    string nombre_cliente, 
                    string apellido_cliente, 
                    string telefono_cliente, 
                    string direccion, 
                    string pais, 
                    string ciudad, 
                    string ip, 
                    string firma, 
                    string info_opcional1, 
                    string info_opcional2, 
                    string info_opcional3, 
                    string lista_codigos_servicio_multicredito, 
                    string lista_nit_codigos_servicio_multicredito, 
                    string lista_valores_con_iva, 
                    string lista_valores_iva, 
                    string total_codigos_servicio, 
                    string fotografiaurl, 
                    string grabacionurl, 
                    string llamadaconfirmacionnumero, 
                    string facebook, 
                    string urlretorno, 
                    string CodigoDelBanco, 
                    string TipoDeUsuario, 
                    string latitud, 
                    string longitud, 
                    string exactitud, 
                    out string errorsms, 
                    out string url, 
                    out string numerotransaccion) {
            Movilway.API.PSE_WS.Iniciar_PagoRequest inValue = new Movilway.API.PSE_WS.Iniciar_PagoRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.referencia = referencia;
            inValue.total_con_iva = total_con_iva;
            inValue.valor_iva = valor_iva;
            inValue.descripcion_pago = descripcion_pago;
            inValue.email = email;
            inValue.Id_cliente = Id_cliente;
            inValue.nombre_cliente = nombre_cliente;
            inValue.apellido_cliente = apellido_cliente;
            inValue.telefono_cliente = telefono_cliente;
            inValue.direccion = direccion;
            inValue.pais = pais;
            inValue.ciudad = ciudad;
            inValue.ip = ip;
            inValue.firma = firma;
            inValue.info_opcional1 = info_opcional1;
            inValue.info_opcional2 = info_opcional2;
            inValue.info_opcional3 = info_opcional3;
            inValue.lista_codigos_servicio_multicredito = lista_codigos_servicio_multicredito;
            inValue.lista_nit_codigos_servicio_multicredito = lista_nit_codigos_servicio_multicredito;
            inValue.lista_valores_con_iva = lista_valores_con_iva;
            inValue.lista_valores_iva = lista_valores_iva;
            inValue.total_codigos_servicio = total_codigos_servicio;
            inValue.fotografiaurl = fotografiaurl;
            inValue.grabacionurl = grabacionurl;
            inValue.llamadaconfirmacionnumero = llamadaconfirmacionnumero;
            inValue.facebook = facebook;
            inValue.urlretorno = urlretorno;
            inValue.CodigoDelBanco = CodigoDelBanco;
            inValue.TipoDeUsuario = TipoDeUsuario;
            inValue.latitud = latitud;
            inValue.longitud = longitud;
            inValue.exactitud = exactitud;
            Movilway.API.PSE_WS.Iniciar_PagoResponse retVal = ((Movilway.API.PSE_WS.PSEPortType)(this)).Iniciar_Pago(inValue);
            errorsms = retVal.errorsms;
            url = retVal.url;
            numerotransaccion = retVal.numerotransaccion;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.PSE_WS.Iniciar_PagoResponse> Iniciar_PagoAsync(Movilway.API.PSE_WS.Iniciar_PagoRequest request) {
            return base.Channel.Iniciar_PagoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.PSE_WS.Confirma_Respuesta_PagoResponse Movilway.API.PSE_WS.PSEPortType.Confirma_Respuesta_Pago(Movilway.API.PSE_WS.Confirma_Respuesta_PagoRequest request) {
            return base.Channel.Confirma_Respuesta_Pago(request);
        }
        
        public string Confirma_Respuesta_Pago(
                    string usuario, 
                    string clave, 
                    string llavemd5, 
                    string numerotransaccion, 
                    out string errorsms, 
                    out string int_estado_pago, 
                    out string str_nombre_banco, 
                    out string str_codigo_transaccion, 
                    out string int_ciclo_transaccion, 
                    out string dat_fecha, 
                    out string fechatransaccion, 
                    out string horatransaccion, 
                    out string descripcion_pago, 
                    out string email, 
                    out string nombre_cliente, 
                    out string apellido_cliente, 
                    out string telefono_cliente, 
                    out string direccion, 
                    out string pais, 
                    out string ciudad, 
                    out string info_opcional1, 
                    out string info_opcional2, 
                    out string info_opcional3, 
                    out string firma, 
                    out string ip, 
                    out string total_con_iva, 
                    out string valor_iva) {
            Movilway.API.PSE_WS.Confirma_Respuesta_PagoRequest inValue = new Movilway.API.PSE_WS.Confirma_Respuesta_PagoRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.numerotransaccion = numerotransaccion;
            Movilway.API.PSE_WS.Confirma_Respuesta_PagoResponse retVal = ((Movilway.API.PSE_WS.PSEPortType)(this)).Confirma_Respuesta_Pago(inValue);
            errorsms = retVal.errorsms;
            int_estado_pago = retVal.int_estado_pago;
            str_nombre_banco = retVal.str_nombre_banco;
            str_codigo_transaccion = retVal.str_codigo_transaccion;
            int_ciclo_transaccion = retVal.int_ciclo_transaccion;
            dat_fecha = retVal.dat_fecha;
            fechatransaccion = retVal.fechatransaccion;
            horatransaccion = retVal.horatransaccion;
            descripcion_pago = retVal.descripcion_pago;
            email = retVal.email;
            nombre_cliente = retVal.nombre_cliente;
            apellido_cliente = retVal.apellido_cliente;
            telefono_cliente = retVal.telefono_cliente;
            direccion = retVal.direccion;
            pais = retVal.pais;
            ciudad = retVal.ciudad;
            info_opcional1 = retVal.info_opcional1;
            info_opcional2 = retVal.info_opcional2;
            info_opcional3 = retVal.info_opcional3;
            firma = retVal.firma;
            ip = retVal.ip;
            total_con_iva = retVal.total_con_iva;
            valor_iva = retVal.valor_iva;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.PSE_WS.Confirma_Respuesta_PagoResponse> Confirma_Respuesta_PagoAsync(Movilway.API.PSE_WS.Confirma_Respuesta_PagoRequest request) {
            return base.Channel.Confirma_Respuesta_PagoAsync(request);
        }
    }
}
