//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.QueryPaymentReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Input", Namespace="http://scioglobalgroup.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class Input : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movilway.API.QueryPaymentReference.Input.ArrayOfString ExtendedDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Client {
            get {
                return this.ClientField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientField, value) != true)) {
                    this.ClientField = value;
                    this.RaisePropertyChanged("Client");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((object.ReferenceEquals(this.AmountField, value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public Movilway.API.QueryPaymentReference.Input.ArrayOfString ExtendedData {
            get {
                return this.ExtendedDataField;
            }
            set {
                if ((object.ReferenceEquals(this.ExtendedDataField, value) != true)) {
                    this.ExtendedDataField = value;
                    this.RaisePropertyChanged("ExtendedData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
        
        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
        [System.Runtime.Serialization.CollectionDataContractAttribute(Name="Input.ArrayOfString", Namespace="http://scioglobalgroup.com/webservices/", ItemName="string")]
        [System.SerializableAttribute()]
        public class ArrayOfString : System.Collections.Generic.List<string> {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Output", Namespace="http://scioglobalgroup.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class Output : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionId {
            get {
                return this.TransactionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionIdField, value) != true)) {
                    this.TransactionIdField = value;
                    this.RaisePropertyChanged("TransactionId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputQuery", Namespace="http://schemas.datacontract.org/2004/07/Movilway.IProtocolWCF.Contract.Data")]
    [System.SerializableAttribute()]
    public partial class OutputQuery : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataDescriptorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FeeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdAutorizationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Movilway.API.QueryPaymentReference.QueryType QueryResultTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponseCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataDescriptor {
            get {
                return this.DataDescriptorField;
            }
            set {
                if ((object.ReferenceEquals(this.DataDescriptorField, value) != true)) {
                    this.DataDescriptorField = value;
                    this.RaisePropertyChanged("DataDescriptor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Details {
            get {
                return this.DetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.DetailsField, value) != true)) {
                    this.DetailsField = value;
                    this.RaisePropertyChanged("Details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Fee {
            get {
                return this.FeeField;
            }
            set {
                if ((this.FeeField.Equals(value) != true)) {
                    this.FeeField = value;
                    this.RaisePropertyChanged("Fee");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAutorization {
            get {
                return this.IdAutorizationField;
            }
            set {
                if ((object.ReferenceEquals(this.IdAutorizationField, value) != true)) {
                    this.IdAutorizationField = value;
                    this.RaisePropertyChanged("IdAutorization");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Movilway.API.QueryPaymentReference.QueryType QueryResultType {
            get {
                return this.QueryResultTypeField;
            }
            set {
                if ((this.QueryResultTypeField.Equals(value) != true)) {
                    this.QueryResultTypeField = value;
                    this.RaisePropertyChanged("QueryResultType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResponseCode {
            get {
                return this.ResponseCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseCodeField, value) != true)) {
                    this.ResponseCodeField = value;
                    this.RaisePropertyChanged("ResponseCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryType", Namespace="http://schemas.datacontract.org/2004/07/Movilway.IProtocolWCF.Contract.Data")]
    public enum QueryType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Single = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Multiple = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scioglobalgroup.com/webservices/", ConfigurationName="QueryPaymentReference.webservices")]
    public interface webservices {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/Reload", ReplyAction="http://scioglobalgroup.com/webservices/webservices/ReloadResponse")]
        Movilway.API.QueryPaymentReference.Output Reload(Movilway.API.QueryPaymentReference.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/Reload", ReplyAction="http://scioglobalgroup.com/webservices/webservices/ReloadResponse")]
        System.Threading.Tasks.Task<Movilway.API.QueryPaymentReference.Output> ReloadAsync(Movilway.API.QueryPaymentReference.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/Revert", ReplyAction="http://scioglobalgroup.com/webservices/webservices/RevertResponse")]
        Movilway.API.QueryPaymentReference.Output Revert(Movilway.API.QueryPaymentReference.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/Revert", ReplyAction="http://scioglobalgroup.com/webservices/webservices/RevertResponse")]
        System.Threading.Tasks.Task<Movilway.API.QueryPaymentReference.Output> RevertAsync(Movilway.API.QueryPaymentReference.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/GetVersion", ReplyAction="http://scioglobalgroup.com/webservices/webservices/GetVersionResponse")]
        string[] GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/GetVersion", ReplyAction="http://scioglobalgroup.com/webservices/webservices/GetVersionResponse")]
        System.Threading.Tasks.Task<string[]> GetVersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface webservicesChannel : Movilway.API.QueryPaymentReference.webservices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class webservicesClient : System.ServiceModel.ClientBase<Movilway.API.QueryPaymentReference.webservices>, Movilway.API.QueryPaymentReference.webservices {
        
        public webservicesClient() {
        }
        
        public webservicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public webservicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webservicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public webservicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Movilway.API.QueryPaymentReference.Output Reload(Movilway.API.QueryPaymentReference.Input input) {
            return base.Channel.Reload(input);
        }
        
        public System.Threading.Tasks.Task<Movilway.API.QueryPaymentReference.Output> ReloadAsync(Movilway.API.QueryPaymentReference.Input input) {
            return base.Channel.ReloadAsync(input);
        }
        
        public Movilway.API.QueryPaymentReference.Output Revert(Movilway.API.QueryPaymentReference.Input input) {
            return base.Channel.Revert(input);
        }
        
        public System.Threading.Tasks.Task<Movilway.API.QueryPaymentReference.Output> RevertAsync(Movilway.API.QueryPaymentReference.Input input) {
            return base.Channel.RevertAsync(input);
        }
        
        public string[] GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string[]> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://scioglobalgroup.com/webservices/", ConfigurationName="QueryPaymentReference.queries")]
    public interface queries {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/Query", ReplyAction="http://scioglobalgroup.com/webservices/queries/QueryResponse")]
        Movilway.API.QueryPaymentReference.OutputQuery Query(Movilway.API.QueryPaymentReference.Input input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://scioglobalgroup.com/webservices/Query", ReplyAction="http://scioglobalgroup.com/webservices/queries/QueryResponse")]
        System.Threading.Tasks.Task<Movilway.API.QueryPaymentReference.OutputQuery> QueryAsync(Movilway.API.QueryPaymentReference.Input input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface queriesChannel : Movilway.API.QueryPaymentReference.queries, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class queriesClient : System.ServiceModel.ClientBase<Movilway.API.QueryPaymentReference.queries>, Movilway.API.QueryPaymentReference.queries {
        
        public queriesClient() {
        }
        
        public queriesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public queriesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public queriesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public queriesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Movilway.API.QueryPaymentReference.OutputQuery Query(Movilway.API.QueryPaymentReference.Input input) {
            return base.Channel.Query(input);
        }
        
        public System.Threading.Tasks.Task<Movilway.API.QueryPaymentReference.OutputQuery> QueryAsync(Movilway.API.QueryPaymentReference.Input input) {
            return base.Channel.QueryAsync(input);
        }
    }
}
