//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.TDC_WS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://puntodepago.plataformadepago.com/secure/webservices", ConfigurationName="TDC_WS.ProcesarTarjetaCreditoPortType")]
    public interface ProcesarTarjetaCreditoPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Verificar_Tarjeta_Tipo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.TDC_WS.Verificar_Tarjeta_TipoResponse Verificar_Tarjeta_Tipo(Movilway.API.TDC_WS.Verificar_Tarjeta_TipoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Verificar_Tarjeta_Tipo", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.TDC_WS.Verificar_Tarjeta_TipoResponse> Verificar_Tarjeta_TipoAsync(Movilway.API.TDC_WS.Verificar_Tarjeta_TipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Procesar_Tarjeta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.TDC_WS.Procesar_TarjetaResponse Procesar_Tarjeta(Movilway.API.TDC_WS.Procesar_TarjetaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Procesar_Tarjeta", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.TDC_WS.Procesar_TarjetaResponse> Procesar_TarjetaAsync(Movilway.API.TDC_WS.Procesar_TarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Reversar_Transaccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.TDC_WS.Reversar_TransaccionResponse Reversar_Transaccion(Movilway.API.TDC_WS.Reversar_TransaccionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Reversar_Transaccion", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.TDC_WS.Reversar_TransaccionResponse> Reversar_TransaccionAsync(Movilway.API.TDC_WS.Reversar_TransaccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Confirmar_Transaccion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.TDC_WS.Confirmar_TransaccionResponse Confirmar_Transaccion(Movilway.API.TDC_WS.Confirmar_TransaccionRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Confirmar_Transaccion", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.TDC_WS.Confirmar_TransaccionResponse> Confirmar_TransaccionAsync(Movilway.API.TDC_WS.Confirmar_TransaccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Email_De_Cobro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.TDC_WS.Email_De_CobroResponse Email_De_Cobro(Movilway.API.TDC_WS.Email_De_CobroRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Email_De_Cobro", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.TDC_WS.Email_De_CobroResponse> Email_De_CobroAsync(Movilway.API.TDC_WS.Email_De_CobroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Link_De_Cobro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.TDC_WS.Link_De_CobroResponse Link_De_Cobro(Movilway.API.TDC_WS.Link_De_CobroRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Link_De_Cobro", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.TDC_WS.Link_De_CobroResponse> Link_De_CobroAsync(Movilway.API.TDC_WS.Link_De_CobroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Pasarela", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Movilway.API.TDC_WS.PasarelaResponse Pasarela(Movilway.API.TDC_WS.PasarelaRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="https://puntodepago.plataformadepago.com/secure/webservices/ProcesarTarjetaCredit" +
            "o.do/Pasarela", ReplyAction="*")]
        System.Threading.Tasks.Task<Movilway.API.TDC_WS.PasarelaResponse> PasarelaAsync(Movilway.API.TDC_WS.PasarelaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Verificar_Tarjeta_Tipo", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Verificar_Tarjeta_TipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string tctipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string tcnumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string ip;
        
        public Verificar_Tarjeta_TipoRequest() {
        }
        
        public Verificar_Tarjeta_TipoRequest(string usuario, string clave, string llavemd5, string tctipo, string tcnumero, string ip) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.tctipo = tctipo;
            this.tcnumero = tcnumero;
            this.ip = ip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Verificar_Tarjeta_TipoResponse", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Verificar_Tarjeta_TipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string codigoderespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string mensajesistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string fechatransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string IPproveedordeinternet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string IPlatitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string IPlongitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string IPciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string IPpais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string IPcontinente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string IPzonahoraria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string IPcodigoisopais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string Tipo;
        
        public Verificar_Tarjeta_TipoResponse() {
        }
        
        public Verificar_Tarjeta_TipoResponse(string respuesta, string codigoderespuesta, string mensajesistema, string fechatransaccion, string IPproveedordeinternet, string IPlatitud, string IPlongitud, string IPciudad, string IPpais, string IPcontinente, string IPzonahoraria, string IPcodigoisopais, string Tipo) {
            this.respuesta = respuesta;
            this.codigoderespuesta = codigoderespuesta;
            this.mensajesistema = mensajesistema;
            this.fechatransaccion = fechatransaccion;
            this.IPproveedordeinternet = IPproveedordeinternet;
            this.IPlatitud = IPlatitud;
            this.IPlongitud = IPlongitud;
            this.IPciudad = IPciudad;
            this.IPpais = IPpais;
            this.IPcontinente = IPcontinente;
            this.IPzonahoraria = IPzonahoraria;
            this.IPcodigoisopais = IPcodigoisopais;
            this.Tipo = Tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Procesar_Tarjeta", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Procesar_TarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string naturaleza;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string tipodedocumentoidentidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string numerodedocumentoidentidad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string tctipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string tipocuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string tcnumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string tcmesexpiracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string tcanoexpiracion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string tccodigodeseguridad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string cuotas;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public string codigopostal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string pais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string ciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string ip;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=23)]
        public string valor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=24)]
        public string iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=25)]
        public string baseiva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=26)]
        public string descripcionpago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=27)]
        public string extra1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=28)]
        public string extra2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=29)]
        public string extra3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=30)]
        public string fotografiaurl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=31)]
        public string grabacionurl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=32)]
        public string llamadaconfirmacionnumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=33)]
        public string facebook;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=34)]
        public string verifiedcc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=35)]
        public string firma;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=36)]
        public string debitoautomatico_periodo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=37)]
        public string debitoautomatico_desde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=38)]
        public string debitoautomatico_hasta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=39)]
        public string latitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=40)]
        public string longitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=41)]
        public string exactitud;
        
        public Procesar_TarjetaRequest() {
        }
        
        public Procesar_TarjetaRequest(
                    string usuario, 
                    string clave, 
                    string llavemd5, 
                    string naturaleza, 
                    string nombres, 
                    string apellidos, 
                    string tipodedocumentoidentidad, 
                    string numerodedocumentoidentidad, 
                    string tctipo, 
                    string tipocuenta, 
                    string tcnumero, 
                    string tcmesexpiracion, 
                    string tcanoexpiracion, 
                    string tccodigodeseguridad, 
                    string cuotas, 
                    string direccion, 
                    string codigopostal, 
                    string pais, 
                    string ciudad, 
                    string telefono, 
                    string email, 
                    string ip, 
                    string moneda, 
                    string valor, 
                    string iva, 
                    string baseiva, 
                    string descripcionpago, 
                    string extra1, 
                    string extra2, 
                    string extra3, 
                    string fotografiaurl, 
                    string grabacionurl, 
                    string llamadaconfirmacionnumero, 
                    string facebook, 
                    string verifiedcc, 
                    string firma, 
                    string debitoautomatico_periodo, 
                    string debitoautomatico_desde, 
                    string debitoautomatico_hasta, 
                    string latitud, 
                    string longitud, 
                    string exactitud) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.naturaleza = naturaleza;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.tipodedocumentoidentidad = tipodedocumentoidentidad;
            this.numerodedocumentoidentidad = numerodedocumentoidentidad;
            this.tctipo = tctipo;
            this.tipocuenta = tipocuenta;
            this.tcnumero = tcnumero;
            this.tcmesexpiracion = tcmesexpiracion;
            this.tcanoexpiracion = tcanoexpiracion;
            this.tccodigodeseguridad = tccodigodeseguridad;
            this.cuotas = cuotas;
            this.direccion = direccion;
            this.codigopostal = codigopostal;
            this.pais = pais;
            this.ciudad = ciudad;
            this.telefono = telefono;
            this.email = email;
            this.ip = ip;
            this.moneda = moneda;
            this.valor = valor;
            this.iva = iva;
            this.baseiva = baseiva;
            this.descripcionpago = descripcionpago;
            this.extra1 = extra1;
            this.extra2 = extra2;
            this.extra3 = extra3;
            this.fotografiaurl = fotografiaurl;
            this.grabacionurl = grabacionurl;
            this.llamadaconfirmacionnumero = llamadaconfirmacionnumero;
            this.facebook = facebook;
            this.verifiedcc = verifiedcc;
            this.firma = firma;
            this.debitoautomatico_periodo = debitoautomatico_periodo;
            this.debitoautomatico_desde = debitoautomatico_desde;
            this.debitoautomatico_hasta = debitoautomatico_hasta;
            this.latitud = latitud;
            this.longitud = longitud;
            this.exactitud = exactitud;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Procesar_TarjetaResponse", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Procesar_TarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string codigoderespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string mensajesistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string fechatransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numerodeautorizacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string numerotransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string respuestadelared;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string logdelared;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string IPproveedordeinternet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string IPlatitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string IPlongitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string IPciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string IPpais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string IPcontinente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string IPzonahoraria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string IPcodigoisopais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public string TARJETAbanco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string TARJETApais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string TARJETAtipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string NombreEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public string CodigoUnico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string Terminal;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=22)]
        public string TipoCuenta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=23)]
        public string TarjetaNumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=24)]
        public string HoraTransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=25)]
        public string Referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=26)]
        public string Recibo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=27)]
        public string CodigoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=28)]
        public string DescripcionCodigoRespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=29)]
        public string MonedaDeConversion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=30)]
        public string ValorTotalConversion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=31)]
        public string ValorIvaConversion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=32)]
        public string ValorBaseIvaConversion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=33)]
        public string AcuerdoDebitoAutomatico;
        
        public Procesar_TarjetaResponse() {
        }
        
        public Procesar_TarjetaResponse(
                    string respuesta, 
                    string codigoderespuesta, 
                    string mensajesistema, 
                    string fechatransaccion, 
                    string numerodeautorizacion, 
                    string numerotransaccion, 
                    string respuestadelared, 
                    string logdelared, 
                    string IPproveedordeinternet, 
                    string IPlatitud, 
                    string IPlongitud, 
                    string IPciudad, 
                    string IPpais, 
                    string IPcontinente, 
                    string IPzonahoraria, 
                    string IPcodigoisopais, 
                    string TARJETAbanco, 
                    string TARJETApais, 
                    string TARJETAtipo, 
                    string NombreEmpresa, 
                    string CodigoUnico, 
                    string Terminal, 
                    string TipoCuenta, 
                    string TarjetaNumero, 
                    string HoraTransaccion, 
                    string Referencia, 
                    string Recibo, 
                    string CodigoRespuesta, 
                    string DescripcionCodigoRespuesta, 
                    string MonedaDeConversion, 
                    string ValorTotalConversion, 
                    string ValorIvaConversion, 
                    string ValorBaseIvaConversion, 
                    string AcuerdoDebitoAutomatico) {
            this.respuesta = respuesta;
            this.codigoderespuesta = codigoderespuesta;
            this.mensajesistema = mensajesistema;
            this.fechatransaccion = fechatransaccion;
            this.numerodeautorizacion = numerodeautorizacion;
            this.numerotransaccion = numerotransaccion;
            this.respuestadelared = respuestadelared;
            this.logdelared = logdelared;
            this.IPproveedordeinternet = IPproveedordeinternet;
            this.IPlatitud = IPlatitud;
            this.IPlongitud = IPlongitud;
            this.IPciudad = IPciudad;
            this.IPpais = IPpais;
            this.IPcontinente = IPcontinente;
            this.IPzonahoraria = IPzonahoraria;
            this.IPcodigoisopais = IPcodigoisopais;
            this.TARJETAbanco = TARJETAbanco;
            this.TARJETApais = TARJETApais;
            this.TARJETAtipo = TARJETAtipo;
            this.NombreEmpresa = NombreEmpresa;
            this.CodigoUnico = CodigoUnico;
            this.Terminal = Terminal;
            this.TipoCuenta = TipoCuenta;
            this.TarjetaNumero = TarjetaNumero;
            this.HoraTransaccion = HoraTransaccion;
            this.Referencia = Referencia;
            this.Recibo = Recibo;
            this.CodigoRespuesta = CodigoRespuesta;
            this.DescripcionCodigoRespuesta = DescripcionCodigoRespuesta;
            this.MonedaDeConversion = MonedaDeConversion;
            this.ValorTotalConversion = ValorTotalConversion;
            this.ValorIvaConversion = ValorIvaConversion;
            this.ValorBaseIvaConversion = ValorBaseIvaConversion;
            this.AcuerdoDebitoAutomatico = AcuerdoDebitoAutomatico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Reversar_Transaccion", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Reversar_TransaccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string numerodetransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numerodeautorizacion;
        
        public Reversar_TransaccionRequest() {
        }
        
        public Reversar_TransaccionRequest(string usuario, string clave, string llavemd5, string numerodetransaccion, string numerodeautorizacion) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.numerodetransaccion = numerodetransaccion;
            this.numerodeautorizacion = numerodeautorizacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Reversar_TransaccionResponse", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Reversar_TransaccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string codigoderespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string mensajesistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string fechatransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numerodeautorizacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string numerodetransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string respuestadelared;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string logdelared;
        
        public Reversar_TransaccionResponse() {
        }
        
        public Reversar_TransaccionResponse(string respuesta, string codigoderespuesta, string mensajesistema, string fechatransaccion, string numerodeautorizacion, string numerodetransaccion, string respuestadelared, string logdelared) {
            this.respuesta = respuesta;
            this.codigoderespuesta = codigoderespuesta;
            this.mensajesistema = mensajesistema;
            this.fechatransaccion = fechatransaccion;
            this.numerodeautorizacion = numerodeautorizacion;
            this.numerodetransaccion = numerodetransaccion;
            this.respuestadelared = respuestadelared;
            this.logdelared = logdelared;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Confirmar_Transaccion", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Confirmar_TransaccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string numerodetransaccion;
        
        public Confirmar_TransaccionRequest() {
        }
        
        public Confirmar_TransaccionRequest(string usuario, string clave, string llavemd5, string numerodetransaccion) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.numerodetransaccion = numerodetransaccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Confirmar_TransaccionResponse", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Confirmar_TransaccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string codigoderespuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string mensajesistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string fechatransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string numerodeautorizacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string numerodetransaccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string respuestadelared;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string logdelared;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string IPproveedordeinternet;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string IPlatitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string IPlongitud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string IPciudad;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string IPpais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string IPcontinente;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string IPzonahoraria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string IPcodigoisopais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public string TARJETAbanco;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string TARJETApais;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=18)]
        public string TARJETAtipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=19)]
        public string extra1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=20)]
        public string extra2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=21)]
        public string extra3;
        
        public Confirmar_TransaccionResponse() {
        }
        
        public Confirmar_TransaccionResponse(
                    string respuesta, 
                    string codigoderespuesta, 
                    string mensajesistema, 
                    string fechatransaccion, 
                    string numerodeautorizacion, 
                    string numerodetransaccion, 
                    string respuestadelared, 
                    string logdelared, 
                    string IPproveedordeinternet, 
                    string IPlatitud, 
                    string IPlongitud, 
                    string IPciudad, 
                    string IPpais, 
                    string IPcontinente, 
                    string IPzonahoraria, 
                    string IPcodigoisopais, 
                    string TARJETAbanco, 
                    string TARJETApais, 
                    string TARJETAtipo, 
                    string extra1, 
                    string extra2, 
                    string extra3) {
            this.respuesta = respuesta;
            this.codigoderespuesta = codigoderespuesta;
            this.mensajesistema = mensajesistema;
            this.fechatransaccion = fechatransaccion;
            this.numerodeautorizacion = numerodeautorizacion;
            this.numerodetransaccion = numerodetransaccion;
            this.respuestadelared = respuestadelared;
            this.logdelared = logdelared;
            this.IPproveedordeinternet = IPproveedordeinternet;
            this.IPlatitud = IPlatitud;
            this.IPlongitud = IPlongitud;
            this.IPciudad = IPciudad;
            this.IPpais = IPpais;
            this.IPcontinente = IPcontinente;
            this.IPzonahoraria = IPzonahoraria;
            this.IPcodigoisopais = IPcodigoisopais;
            this.TARJETAbanco = TARJETAbanco;
            this.TARJETApais = TARJETApais;
            this.TARJETAtipo = TARJETAtipo;
            this.extra1 = extra1;
            this.extra2 = extra2;
            this.extra3 = extra3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Email_De_Cobro", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Email_De_CobroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string valor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string baseiva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string descripcion;
        
        public Email_De_CobroRequest() {
        }
        
        public Email_De_CobroRequest(string usuario, string clave, string llavemd5, string email, string referencia, string moneda, string valor, string iva, string baseiva, string descripcion) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.email = email;
            this.referencia = referencia;
            this.moneda = moneda;
            this.valor = valor;
            this.iva = iva;
            this.baseiva = baseiva;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Email_De_CobroResponse", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Email_De_CobroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string mensajesistema;
        
        public Email_De_CobroResponse() {
        }
        
        public Email_De_CobroResponse(string respuesta, string mensajesistema) {
            this.respuesta = respuesta;
            this.mensajesistema = mensajesistema;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Link_De_Cobro", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Link_De_CobroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string clave;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string valor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string baseiva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string descripcion;
        
        public Link_De_CobroRequest() {
        }
        
        public Link_De_CobroRequest(string usuario, string clave, string llavemd5, string referencia, string moneda, string valor, string iva, string baseiva, string descripcion) {
            this.usuario = usuario;
            this.clave = clave;
            this.llavemd5 = llavemd5;
            this.referencia = referencia;
            this.moneda = moneda;
            this.valor = valor;
            this.iva = iva;
            this.baseiva = baseiva;
            this.descripcion = descripcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Link_De_CobroResponse", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class Link_De_CobroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string mensajesistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string link;
        
        public Link_De_CobroResponse() {
        }
        
        public Link_De_CobroResponse(string respuesta, string mensajesistema, string link) {
            this.respuesta = respuesta;
            this.mensajesistema = mensajesistema;
            this.link = link;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Pasarela", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class PasarelaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string usuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string llavemd5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string referencia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string moneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public string valor;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=5)]
        public string iva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=6)]
        public string baseiva;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=7)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=8)]
        public string urlback;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=9)]
        public string documentonumero;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=10)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=11)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=12)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=13)]
        public string direccion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=14)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=15)]
        public string debitoautomatico_periodo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=16)]
        public string debitoautomatico_desde;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=17)]
        public string debitoautomatico_hasta;
        
        public PasarelaRequest() {
        }
        
        public PasarelaRequest(
                    string usuario, 
                    string llavemd5, 
                    string referencia, 
                    string moneda, 
                    string valor, 
                    string iva, 
                    string baseiva, 
                    string descripcion, 
                    string urlback, 
                    string documentonumero, 
                    string nombres, 
                    string apellidos, 
                    string email, 
                    string direccion, 
                    string telefono, 
                    string debitoautomatico_periodo, 
                    string debitoautomatico_desde, 
                    string debitoautomatico_hasta) {
            this.usuario = usuario;
            this.llavemd5 = llavemd5;
            this.referencia = referencia;
            this.moneda = moneda;
            this.valor = valor;
            this.iva = iva;
            this.baseiva = baseiva;
            this.descripcion = descripcion;
            this.urlback = urlback;
            this.documentonumero = documentonumero;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.email = email;
            this.direccion = direccion;
            this.telefono = telefono;
            this.debitoautomatico_periodo = debitoautomatico_periodo;
            this.debitoautomatico_desde = debitoautomatico_desde;
            this.debitoautomatico_hasta = debitoautomatico_hasta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PasarelaResponse", WrapperNamespace="https://puntodepago.plataformadepago.com/secure/webservices", IsWrapped=true)]
    public partial class PasarelaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string respuesta;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string mensajesistema;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string transaccionnro;
        
        public PasarelaResponse() {
        }
        
        public PasarelaResponse(string respuesta, string mensajesistema, string url, string transaccionnro) {
            this.respuesta = respuesta;
            this.mensajesistema = mensajesistema;
            this.url = url;
            this.transaccionnro = transaccionnro;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProcesarTarjetaCreditoPortTypeChannel : Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProcesarTarjetaCreditoPortTypeClient : System.ServiceModel.ClientBase<Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType>, Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType {
        
        public ProcesarTarjetaCreditoPortTypeClient() {
        }
        
        public ProcesarTarjetaCreditoPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProcesarTarjetaCreditoPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesarTarjetaCreditoPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProcesarTarjetaCreditoPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.TDC_WS.Verificar_Tarjeta_TipoResponse Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType.Verificar_Tarjeta_Tipo(Movilway.API.TDC_WS.Verificar_Tarjeta_TipoRequest request) {
            return base.Channel.Verificar_Tarjeta_Tipo(request);
        }
        
        public string Verificar_Tarjeta_Tipo(
                    string usuario, 
                    string clave, 
                    string llavemd5, 
                    string tctipo, 
                    string tcnumero, 
                    string ip, 
                    out string codigoderespuesta, 
                    out string mensajesistema, 
                    out string fechatransaccion, 
                    out string IPproveedordeinternet, 
                    out string IPlatitud, 
                    out string IPlongitud, 
                    out string IPciudad, 
                    out string IPpais, 
                    out string IPcontinente, 
                    out string IPzonahoraria, 
                    out string IPcodigoisopais, 
                    out string Tipo) {
            Movilway.API.TDC_WS.Verificar_Tarjeta_TipoRequest inValue = new Movilway.API.TDC_WS.Verificar_Tarjeta_TipoRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.tctipo = tctipo;
            inValue.tcnumero = tcnumero;
            inValue.ip = ip;
            Movilway.API.TDC_WS.Verificar_Tarjeta_TipoResponse retVal = ((Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType)(this)).Verificar_Tarjeta_Tipo(inValue);
            codigoderespuesta = retVal.codigoderespuesta;
            mensajesistema = retVal.mensajesistema;
            fechatransaccion = retVal.fechatransaccion;
            IPproveedordeinternet = retVal.IPproveedordeinternet;
            IPlatitud = retVal.IPlatitud;
            IPlongitud = retVal.IPlongitud;
            IPciudad = retVal.IPciudad;
            IPpais = retVal.IPpais;
            IPcontinente = retVal.IPcontinente;
            IPzonahoraria = retVal.IPzonahoraria;
            IPcodigoisopais = retVal.IPcodigoisopais;
            Tipo = retVal.Tipo;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.TDC_WS.Verificar_Tarjeta_TipoResponse> Verificar_Tarjeta_TipoAsync(Movilway.API.TDC_WS.Verificar_Tarjeta_TipoRequest request) {
            return base.Channel.Verificar_Tarjeta_TipoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.TDC_WS.Procesar_TarjetaResponse Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType.Procesar_Tarjeta(Movilway.API.TDC_WS.Procesar_TarjetaRequest request) {
            return base.Channel.Procesar_Tarjeta(request);
        }
        
        public string Procesar_Tarjeta(
                    string usuario, 
                    string clave, 
                    string llavemd5, 
                    string naturaleza, 
                    string nombres, 
                    string apellidos, 
                    string tipodedocumentoidentidad, 
                    string numerodedocumentoidentidad, 
                    string tctipo, 
                    string tipocuenta, 
                    string tcnumero, 
                    string tcmesexpiracion, 
                    string tcanoexpiracion, 
                    string tccodigodeseguridad, 
                    string cuotas, 
                    string direccion, 
                    string codigopostal, 
                    string pais, 
                    string ciudad, 
                    string telefono, 
                    string email, 
                    string ip, 
                    string moneda, 
                    string valor, 
                    string iva, 
                    string baseiva, 
                    string descripcionpago, 
                    string extra1, 
                    string extra2, 
                    string extra3, 
                    string fotografiaurl, 
                    string grabacionurl, 
                    string llamadaconfirmacionnumero, 
                    string facebook, 
                    string verifiedcc, 
                    string firma, 
                    string debitoautomatico_periodo, 
                    string debitoautomatico_desde, 
                    string debitoautomatico_hasta, 
                    string latitud, 
                    string longitud, 
                    string exactitud, 
                    out string codigoderespuesta, 
                    out string mensajesistema, 
                    out string fechatransaccion, 
                    out string numerodeautorizacion, 
                    out string numerotransaccion, 
                    out string respuestadelared, 
                    out string logdelared, 
                    out string IPproveedordeinternet, 
                    out string IPlatitud, 
                    out string IPlongitud, 
                    out string IPciudad, 
                    out string IPpais, 
                    out string IPcontinente, 
                    out string IPzonahoraria, 
                    out string IPcodigoisopais, 
                    out string TARJETAbanco, 
                    out string TARJETApais, 
                    out string TARJETAtipo, 
                    out string NombreEmpresa, 
                    out string CodigoUnico, 
                    out string Terminal, 
                    out string TipoCuenta1, 
                    out string TarjetaNumero, 
                    out string HoraTransaccion, 
                    out string Referencia, 
                    out string Recibo, 
                    out string CodigoRespuesta, 
                    out string DescripcionCodigoRespuesta, 
                    out string MonedaDeConversion, 
                    out string ValorTotalConversion, 
                    out string ValorIvaConversion, 
                    out string ValorBaseIvaConversion, 
                    out string AcuerdoDebitoAutomatico) {
            Movilway.API.TDC_WS.Procesar_TarjetaRequest inValue = new Movilway.API.TDC_WS.Procesar_TarjetaRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.naturaleza = naturaleza;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.tipodedocumentoidentidad = tipodedocumentoidentidad;
            inValue.numerodedocumentoidentidad = numerodedocumentoidentidad;
            inValue.tctipo = tctipo;
            inValue.tipocuenta = tipocuenta;
            inValue.tcnumero = tcnumero;
            inValue.tcmesexpiracion = tcmesexpiracion;
            inValue.tcanoexpiracion = tcanoexpiracion;
            inValue.tccodigodeseguridad = tccodigodeseguridad;
            inValue.cuotas = cuotas;
            inValue.direccion = direccion;
            inValue.codigopostal = codigopostal;
            inValue.pais = pais;
            inValue.ciudad = ciudad;
            inValue.telefono = telefono;
            inValue.email = email;
            inValue.ip = ip;
            inValue.moneda = moneda;
            inValue.valor = valor;
            inValue.iva = iva;
            inValue.baseiva = baseiva;
            inValue.descripcionpago = descripcionpago;
            inValue.extra1 = extra1;
            inValue.extra2 = extra2;
            inValue.extra3 = extra3;
            inValue.fotografiaurl = fotografiaurl;
            inValue.grabacionurl = grabacionurl;
            inValue.llamadaconfirmacionnumero = llamadaconfirmacionnumero;
            inValue.facebook = facebook;
            inValue.verifiedcc = verifiedcc;
            inValue.firma = firma;
            inValue.debitoautomatico_periodo = debitoautomatico_periodo;
            inValue.debitoautomatico_desde = debitoautomatico_desde;
            inValue.debitoautomatico_hasta = debitoautomatico_hasta;
            inValue.latitud = latitud;
            inValue.longitud = longitud;
            inValue.exactitud = exactitud;
            Movilway.API.TDC_WS.Procesar_TarjetaResponse retVal = ((Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType)(this)).Procesar_Tarjeta(inValue);
            codigoderespuesta = retVal.codigoderespuesta;
            mensajesistema = retVal.mensajesistema;
            fechatransaccion = retVal.fechatransaccion;
            numerodeautorizacion = retVal.numerodeautorizacion;
            numerotransaccion = retVal.numerotransaccion;
            respuestadelared = retVal.respuestadelared;
            logdelared = retVal.logdelared;
            IPproveedordeinternet = retVal.IPproveedordeinternet;
            IPlatitud = retVal.IPlatitud;
            IPlongitud = retVal.IPlongitud;
            IPciudad = retVal.IPciudad;
            IPpais = retVal.IPpais;
            IPcontinente = retVal.IPcontinente;
            IPzonahoraria = retVal.IPzonahoraria;
            IPcodigoisopais = retVal.IPcodigoisopais;
            TARJETAbanco = retVal.TARJETAbanco;
            TARJETApais = retVal.TARJETApais;
            TARJETAtipo = retVal.TARJETAtipo;
            NombreEmpresa = retVal.NombreEmpresa;
            CodigoUnico = retVal.CodigoUnico;
            Terminal = retVal.Terminal;
            TipoCuenta1 = retVal.TipoCuenta;
            TarjetaNumero = retVal.TarjetaNumero;
            HoraTransaccion = retVal.HoraTransaccion;
            Referencia = retVal.Referencia;
            Recibo = retVal.Recibo;
            CodigoRespuesta = retVal.CodigoRespuesta;
            DescripcionCodigoRespuesta = retVal.DescripcionCodigoRespuesta;
            MonedaDeConversion = retVal.MonedaDeConversion;
            ValorTotalConversion = retVal.ValorTotalConversion;
            ValorIvaConversion = retVal.ValorIvaConversion;
            ValorBaseIvaConversion = retVal.ValorBaseIvaConversion;
            AcuerdoDebitoAutomatico = retVal.AcuerdoDebitoAutomatico;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.TDC_WS.Procesar_TarjetaResponse> Procesar_TarjetaAsync(Movilway.API.TDC_WS.Procesar_TarjetaRequest request) {
            return base.Channel.Procesar_TarjetaAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.TDC_WS.Reversar_TransaccionResponse Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType.Reversar_Transaccion(Movilway.API.TDC_WS.Reversar_TransaccionRequest request) {
            return base.Channel.Reversar_Transaccion(request);
        }
        
        public string Reversar_Transaccion(string usuario, string clave, string llavemd5, ref string numerodetransaccion, ref string numerodeautorizacion, out string codigoderespuesta, out string mensajesistema, out string fechatransaccion, out string respuestadelared, out string logdelared) {
            Movilway.API.TDC_WS.Reversar_TransaccionRequest inValue = new Movilway.API.TDC_WS.Reversar_TransaccionRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.numerodetransaccion = numerodetransaccion;
            inValue.numerodeautorizacion = numerodeautorizacion;
            Movilway.API.TDC_WS.Reversar_TransaccionResponse retVal = ((Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType)(this)).Reversar_Transaccion(inValue);
            codigoderespuesta = retVal.codigoderespuesta;
            mensajesistema = retVal.mensajesistema;
            fechatransaccion = retVal.fechatransaccion;
            numerodeautorizacion = retVal.numerodeautorizacion;
            numerodetransaccion = retVal.numerodetransaccion;
            respuestadelared = retVal.respuestadelared;
            logdelared = retVal.logdelared;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.TDC_WS.Reversar_TransaccionResponse> Reversar_TransaccionAsync(Movilway.API.TDC_WS.Reversar_TransaccionRequest request) {
            return base.Channel.Reversar_TransaccionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.TDC_WS.Confirmar_TransaccionResponse Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType.Confirmar_Transaccion(Movilway.API.TDC_WS.Confirmar_TransaccionRequest request) {
            return base.Channel.Confirmar_Transaccion(request);
        }
        
        public string Confirmar_Transaccion(
                    string usuario, 
                    string clave, 
                    string llavemd5, 
                    ref string numerodetransaccion, 
                    out string codigoderespuesta, 
                    out string mensajesistema, 
                    out string fechatransaccion, 
                    out string numerodeautorizacion, 
                    out string respuestadelared, 
                    out string logdelared, 
                    out string IPproveedordeinternet, 
                    out string IPlatitud, 
                    out string IPlongitud, 
                    out string IPciudad, 
                    out string IPpais, 
                    out string IPcontinente, 
                    out string IPzonahoraria, 
                    out string IPcodigoisopais, 
                    out string TARJETAbanco, 
                    out string TARJETApais, 
                    out string TARJETAtipo, 
                    out string extra1, 
                    out string extra2, 
                    out string extra3) {
            Movilway.API.TDC_WS.Confirmar_TransaccionRequest inValue = new Movilway.API.TDC_WS.Confirmar_TransaccionRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.numerodetransaccion = numerodetransaccion;
            Movilway.API.TDC_WS.Confirmar_TransaccionResponse retVal = ((Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType)(this)).Confirmar_Transaccion(inValue);
            codigoderespuesta = retVal.codigoderespuesta;
            mensajesistema = retVal.mensajesistema;
            fechatransaccion = retVal.fechatransaccion;
            numerodeautorizacion = retVal.numerodeautorizacion;
            numerodetransaccion = retVal.numerodetransaccion;
            respuestadelared = retVal.respuestadelared;
            logdelared = retVal.logdelared;
            IPproveedordeinternet = retVal.IPproveedordeinternet;
            IPlatitud = retVal.IPlatitud;
            IPlongitud = retVal.IPlongitud;
            IPciudad = retVal.IPciudad;
            IPpais = retVal.IPpais;
            IPcontinente = retVal.IPcontinente;
            IPzonahoraria = retVal.IPzonahoraria;
            IPcodigoisopais = retVal.IPcodigoisopais;
            TARJETAbanco = retVal.TARJETAbanco;
            TARJETApais = retVal.TARJETApais;
            TARJETAtipo = retVal.TARJETAtipo;
            extra1 = retVal.extra1;
            extra2 = retVal.extra2;
            extra3 = retVal.extra3;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.TDC_WS.Confirmar_TransaccionResponse> Confirmar_TransaccionAsync(Movilway.API.TDC_WS.Confirmar_TransaccionRequest request) {
            return base.Channel.Confirmar_TransaccionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.TDC_WS.Email_De_CobroResponse Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType.Email_De_Cobro(Movilway.API.TDC_WS.Email_De_CobroRequest request) {
            return base.Channel.Email_De_Cobro(request);
        }
        
        public string Email_De_Cobro(string usuario, string clave, string llavemd5, string email, string referencia, string moneda, string valor, string iva, string baseiva, string descripcion, out string mensajesistema) {
            Movilway.API.TDC_WS.Email_De_CobroRequest inValue = new Movilway.API.TDC_WS.Email_De_CobroRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.email = email;
            inValue.referencia = referencia;
            inValue.moneda = moneda;
            inValue.valor = valor;
            inValue.iva = iva;
            inValue.baseiva = baseiva;
            inValue.descripcion = descripcion;
            Movilway.API.TDC_WS.Email_De_CobroResponse retVal = ((Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType)(this)).Email_De_Cobro(inValue);
            mensajesistema = retVal.mensajesistema;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.TDC_WS.Email_De_CobroResponse> Email_De_CobroAsync(Movilway.API.TDC_WS.Email_De_CobroRequest request) {
            return base.Channel.Email_De_CobroAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.TDC_WS.Link_De_CobroResponse Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType.Link_De_Cobro(Movilway.API.TDC_WS.Link_De_CobroRequest request) {
            return base.Channel.Link_De_Cobro(request);
        }
        
        public string Link_De_Cobro(string usuario, string clave, string llavemd5, string referencia, string moneda, string valor, string iva, string baseiva, string descripcion, out string mensajesistema, out string link) {
            Movilway.API.TDC_WS.Link_De_CobroRequest inValue = new Movilway.API.TDC_WS.Link_De_CobroRequest();
            inValue.usuario = usuario;
            inValue.clave = clave;
            inValue.llavemd5 = llavemd5;
            inValue.referencia = referencia;
            inValue.moneda = moneda;
            inValue.valor = valor;
            inValue.iva = iva;
            inValue.baseiva = baseiva;
            inValue.descripcion = descripcion;
            Movilway.API.TDC_WS.Link_De_CobroResponse retVal = ((Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType)(this)).Link_De_Cobro(inValue);
            mensajesistema = retVal.mensajesistema;
            link = retVal.link;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.TDC_WS.Link_De_CobroResponse> Link_De_CobroAsync(Movilway.API.TDC_WS.Link_De_CobroRequest request) {
            return base.Channel.Link_De_CobroAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Movilway.API.TDC_WS.PasarelaResponse Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType.Pasarela(Movilway.API.TDC_WS.PasarelaRequest request) {
            return base.Channel.Pasarela(request);
        }
        
        public string Pasarela(
                    string usuario, 
                    string llavemd5, 
                    string referencia, 
                    string moneda, 
                    string valor, 
                    string iva, 
                    string baseiva, 
                    string descripcion, 
                    string urlback, 
                    string documentonumero, 
                    string nombres, 
                    string apellidos, 
                    string email, 
                    string direccion, 
                    string telefono, 
                    string debitoautomatico_periodo, 
                    string debitoautomatico_desde, 
                    string debitoautomatico_hasta, 
                    out string mensajesistema, 
                    out string url, 
                    out string transaccionnro) {
            Movilway.API.TDC_WS.PasarelaRequest inValue = new Movilway.API.TDC_WS.PasarelaRequest();
            inValue.usuario = usuario;
            inValue.llavemd5 = llavemd5;
            inValue.referencia = referencia;
            inValue.moneda = moneda;
            inValue.valor = valor;
            inValue.iva = iva;
            inValue.baseiva = baseiva;
            inValue.descripcion = descripcion;
            inValue.urlback = urlback;
            inValue.documentonumero = documentonumero;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.email = email;
            inValue.direccion = direccion;
            inValue.telefono = telefono;
            inValue.debitoautomatico_periodo = debitoautomatico_periodo;
            inValue.debitoautomatico_desde = debitoautomatico_desde;
            inValue.debitoautomatico_hasta = debitoautomatico_hasta;
            Movilway.API.TDC_WS.PasarelaResponse retVal = ((Movilway.API.TDC_WS.ProcesarTarjetaCreditoPortType)(this)).Pasarela(inValue);
            mensajesistema = retVal.mensajesistema;
            url = retVal.url;
            transaccionnro = retVal.transaccionnro;
            return retVal.respuesta;
        }
        
        public System.Threading.Tasks.Task<Movilway.API.TDC_WS.PasarelaResponse> PasarelaAsync(Movilway.API.TDC_WS.PasarelaRequest request) {
            return base.Channel.PasarelaAsync(request);
        }
    }
}
