//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.MacroProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceType
    {
        public BalanceType()
        {
            this.MacroProduct = new HashSet<MacroProduct>();
        }
    
        public int BalanceTypeId { get; set; }
        public string BalanceTypeName { get; set; }
        public string BalanceTypeDescription { get; set; }
    
        public virtual ICollection<MacroProduct> MacroProduct { get; set; }
    }
}
