//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.MacroProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SubCategory = new HashSet<SubCategory>();
        }
    
        public int CategoryId { get; set; }
        public int CountryId { get; set; }
        public string CategoryName { get; set; }
        public string StatusId { get; set; }
        public int Rank { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SubCategory> SubCategory { get; set; }
    }
}
