//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.MacroProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonProvider
    {
        public CommonProvider()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int Id_Provider { get; set; }
        public string ProviderName { get; set; }
    
        public virtual ICollection<Product> Product { get; set; }
    }
}
