//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.MacroProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacroProduct
    {
        public MacroProduct()
        {
            this.MacroProductChannel = new HashSet<MacroProductChannel>();
            this.MacroProductField = new HashSet<MacroProductField>();
            this.AccessType = new HashSet<AccessType>();
        }
    
        public int MacroProductId { get; set; }
        public int CountryId { get; set; }
        public int SubcategoryId { get; set; }
        public int BalanceTypeId { get; set; }
        public string MacroProductName { get; set; }
        public double FeePercent { get; set; }
        public double FeePlus { get; set; }
        public bool Reprint { get; set; }
        public int AmountTypeId { get; set; }
        public int Rank { get; set; }
        public bool MandatoryPrint { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Description { get; set; }
        public Nullable<int> OwnerCountryId { get; set; }
        public string CurrencyPurchase { get; set; }
        public string CurrencySale { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public string AmountField { get; set; }
        public string StatusId { get; set; }
        public string Message { get; set; }
        public Nullable<bool> RequireQuery { get; set; }
    
        public virtual AmountType AmountType { get; set; }
        public virtual BalanceType BalanceType { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<MacroProductChannel> MacroProductChannel { get; set; }
        public virtual ICollection<MacroProductField> MacroProductField { get; set; }
        public virtual ICollection<AccessType> AccessType { get; set; }
    }
}
