//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.MacroProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacroProductValue
    {
        public int MacroProductValueId { get; set; }
        public int MacroProductFieldId { get; set; }
        public int MacroProductId { get; set; }
        public int CountryId { get; set; }
        public string ValueName { get; set; }
        public string Value { get; set; }
    
        public virtual MacroProductField MacroProductField { get; set; }
    }
}
