//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movilway.API.Data.MacroProduct
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpCategory
    {
        public MpCategory()
        {
            this.MpCatRelation = new HashSet<MpCatRelation>();
        }
    
        public int Id_Category { get; set; }
        public string CatName { get; set; }
    
        public virtual ICollection<MpCatRelation> MpCatRelation { get; set; }
    }
}
